spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3428238749
    url: jdbc:mysql://47.56.130.126:3306/love?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    #遇到错误时继续
    continue-on-error: true
    platform: mysql
    #初始化数据库
    #always为始终执行初始化，embedded只初始化内存数据库（默认值）,如h2等，never为不执行初始化。
    initialization-mode: never
    #启动时需要初始化的建表语句
    schema:
    - "classpath:schema-mysql.sql"
    #初始化的数据
    data:
    - "classpath:data-mysql.sql"
    #连接池
    hikari:
      #此属性控制客户端（即您）将等待来自池的连接的最大毫秒数
      connection-timeout: 4000
      #此属性控制允许连接在池中闲置的最长时间
      idle-timeout: 3000
      #该属性控制HikariCP尝试在池中维护的最小空闲连接数
      minimum-idle:
      #此属性控制池中连接的最大生存期。正在使用的连接永远不会退休，只有在关闭后才会被删除。
      #在逐个连接的基础上，应用较小的负面衰减来避免池中的大量消失。 我们强烈建议设置此值
      maxLifetime: 3000
      #池名字 用来区分
      pool-name: loveHikariCP
      #自动提交 控制从池返回的连接的默认自动提交行为
      autoCommit: true
